addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.8.2")
addSbtPlugin("org.wartremover"           % "sbt-wartremover" % "2.4.10" cross CrossVersion.full)
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"    % "2.4.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"    % "0.1.13")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "3.9.4")
addSbtPlugin("com.github.gseitz" % "sbt-release" % "1.0.13")